export * from './administraoDeTimes.service';
import { AdministraoDeTimesService } from './administraoDeTimes.service';
export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './eventoController.service';
import { EventoControllerService } from './eventoController.service';
export * from './partidas.service';
import { PartidasService } from './partidas.service';
export * from './times.service';
import { TimesService } from './times.service';
export const APIS = [AdministraoDeTimesService, AuthenticationControllerService, EventoControllerService, PartidasService, TimesService];
