/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcaoJogoDTO { 
    jogadorId: number;
    tipoAcao: AcaoJogoDTO.TipoAcaoEnum;
}
export namespace AcaoJogoDTO {
    export const TipoAcaoEnum = {
        Gol: 'GOL',
        Assistencia: 'ASSISTENCIA',
        Defesa: 'DEFESA',
        Falta: 'FALTA',
        Impedimento: 'IMPEDIMENTO'
    } as const;
    export type TipoAcaoEnum = typeof TipoAcaoEnum[keyof typeof TipoAcaoEnum];
}


