/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoTransferencia } from './historicoTransferencia';
import { User } from './user';
import { Partida } from './partida';
import { Time } from './time';
import { Inscricao } from './inscricao';


export interface Evento { 
    id?: number;
    usuario?: User;
    dataHorarioEvento?: string;
    nome?: string;
    dataCriacao?: string;
    localEvento?: string;
    latitude?: number;
    longitude?: number;
    jogadoresPorTime?: number;
    totalPartidasDefinidas?: number;
    status?: Evento.StatusEnum;
    corPrimaria?: string;
    corSecundaria?: string;
    times?: Array<Time>;
    inscricoes?: Array<Inscricao>;
    partidas?: Array<Partida>;
    historicoTransferencias?: Array<HistoricoTransferencia>;
}
export namespace Evento {
    export const StatusEnum = {
        Ativo: 'ATIVO',
        Finalizado: 'FINALIZADO'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


