/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventoResponseDTO { 
    id?: number;
    nome?: string;
    local?: string;
    latitude?: number;
    longitude?: number;
    dataHorario?: string;
    usuarioId?: number;
    usuarioLogin?: string;
    usuarioNome?: string;
    isOrganizer?: boolean;
    status?: string;
    totalPartidasDefinidas?: number;
}

