/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EventoResponseDTO {
  id?: number;
  nome?: string;
  local?: string;
  dataHorario?: string;
  usuarioId?: number;
  usuarioLogin?: string;
  usuarioNome?: string;
  latitude?: number;
  longitude?: number;
  isOrganizer?: boolean;
  status?: string;
}
