/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoricoPontuacao { 
    id?: number;
    pontosAntes?: number;
    pontosDepois?: number;
    variacao?: number;
    dataRegistro?: string;
    jogador?: any | null;
    partida?: any | null;
}

