/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoricoPontuacao { 
    id?: number;
    pontosAntes?: number;
    pontosDepois?: number;
    variacao?: number;
    dataRegistro?: string;
    acao?: HistoricoPontuacao.AcaoEnum;
    jogador?: any | null;
    partida?: any | null;
}
export namespace HistoricoPontuacao {
    export const AcaoEnum = {
        Gol: 'GOL',
        Assistencia: 'ASSISTENCIA',
        Defesa: 'DEFESA',
        Falta: 'FALTA',
        Impedimento: 'IMPEDIMENTO'
    } as const;
    export type AcaoEnum = typeof AcaoEnum[keyof typeof AcaoEnum];
}


