/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Partida } from './partida';
import { Time } from './time';


export interface HistoricoTransferencia { 
    id?: number;
    dataTransferencia?: string;
    evento?: any | null;
    partidaGatilho?: Partida;
    jogador?: User;
    timeOrigem?: Time;
    timeDestino?: Time;
}

