/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Evento } from './evento';
import { Time } from './time';


export interface Inscricao { 
    id?: number;
    partidasJogadas?: number;
    evento?: Evento;
    jogador?: User;
    timeAtual?: Time;
}

