/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InscricaoResponseDTO { 
    id?: number;
    jogadorId?: number;
    jogadorNome?: string;
    jogadorEmail?: string;
    partidasJogadas?: number;
    timeAtualId?: number;
    timeAtualNome?: string;
    dataInscricao?: string;
    status?: string;
}

