/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Evento } from './evento';
import { Time } from './time';


export interface Inscricao { 
    id?: number;
    partidasJogadas?: number;
    evento?: Evento;
    jogador?: User;
    timeAtual?: Time;
    dataInscricao?: string;
    status?: Inscricao.StatusEnum;
}
export namespace Inscricao {
    export const StatusEnum = {
        Pendente: 'PENDENTE',
        Aprovada: 'APROVADA',
        Rejeitada: 'REJEITADA'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


