/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JogadorResumoDTO { 
    id?: number;
    nome?: string;
    pontosHabilidade?: number;
    nivelHabilidade?: JogadorResumoDTO.NivelHabilidadeEnum;
    partidasJogadas?: number;
}
export namespace JogadorResumoDTO {
    export const NivelHabilidadeEnum = {
        Craque: 'CRAQUE',
        Mediano: 'MEDIANO',
        PernaDePau: 'PERNA_DE_PAU'
    } as const;
    export type NivelHabilidadeEnum = typeof NivelHabilidadeEnum[keyof typeof NivelHabilidadeEnum];
}


