/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Partida } from './partida';
import { Time } from './time';


export interface ParticipacaoDesempenho { 
    id?: number;
    gols?: number;
    passes?: number;
    defesas?: number;
    partida?: Partida;
    jogador?: User;
    timeNaPartida?: Time;
}

