/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PartidaResponseDTO { 
    id?: number;
    dataPartida?: string;
    status?: string;
    timeANome?: string;
    timeAPlacar?: number;
    timeAId?: number;
    timeBNome?: string;
    timeBPlacar?: number;
    timeBId?: number;
    eventoId?: number;
}

