/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoPontuacao } from './historicoPontuacao';
import { HistoricoTransferencia } from './historicoTransferencia';
import { Time } from './time';
import { ParticipacaoDesempenho } from './participacaoDesempenho';


export interface Partida { 
    id?: number;
    dataPartida?: string;
    status?: Partida.StatusEnum;
    timeAPlacar?: number;
    timeBPlacar?: number;
    evento?: any | null;
    timeA?: Time;
    timeB?: Time;
    participacoes?: Array<ParticipacaoDesempenho>;
    historicoPontuacao?: Array<HistoricoPontuacao>;
    historicoTransferencias?: Array<HistoricoTransferencia>;
}
export namespace Partida {
    export const StatusEnum = {
        Jogada: 'JOGADA',
        Cancelada: 'CANCELADA',
        EmAndamento: 'EM_ANDAMENTO',
        AguardandoInicio: 'AGUARDANDO_INICIO'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


