/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PontuacaoManualDTO { 
    acao?: PontuacaoManualDTO.AcaoEnum;
}
export namespace PontuacaoManualDTO {
    export const AcaoEnum = {
        Gol: 'GOL',
        Assistencia: 'ASSISTENCIA',
        Defesa: 'DEFESA',
        Falta: 'FALTA',
        Impedimento: 'IMPEDIMENTO'
    } as const;
    export type AcaoEnum = typeof AcaoEnum[keyof typeof AcaoEnum];
}


