/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDTO { 
    login: string;
    password: string;
    nome: string;
    role?: RegisterDTO.RoleEnum;
}
export namespace RegisterDTO {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


