/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Partida } from './partida';
import { Inscricao } from './inscricao';
import { ParticipacaoDesempenho } from './participacaoDesempenho';


export interface Time { 
    id?: number;
    nome?: string;
    cor?: string;
    timeDeEspera?: boolean;
    status?: Time.StatusEnum;
    evento?: any | null;
    inscricoes?: Array<Inscricao>;
    partidasComoTimeA?: Array<Partida>;
    partidasComoTimeB?: Array<Partida>;
    participacoes?: Array<ParticipacaoDesempenho>;
}
export namespace Time {
    export const StatusEnum = {
        Inoperante: 'INOPERANTE',
        Ativo: 'ATIVO',
        Espera: 'ESPERA'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


