/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JogadorResumoDTO } from './jogadorResumoDTO';


export interface TimeComJogadoresDTO { 
    timeId?: number;
    nome?: string;
    status?: TimeComJogadoresDTO.StatusEnum;
    isTimeDeEspera?: boolean;
    jogadores?: Array<JogadorResumoDTO>;
}
export namespace TimeComJogadoresDTO {
    export const StatusEnum = {
        Inoperante: 'INOPERANTE',
        Ativo: 'ATIVO',
        Espera: 'ESPERA'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


