/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JogadorDTO } from './jogadorDTO';


export interface TimeResponseDTO { 
    id?: number;
    nome?: string;
    cor?: string;
    timeDeEspera?: boolean;
    status?: string;
    jogadores?: Array<JogadorDTO>;
}

