/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface User { 
    id?: number;
    nome?: string;
    email?: string;
    password?: string;
    role?: string;
    enabled?: boolean;
    username?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
    accountNonLocked?: boolean;
}

