/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDTO { 
    id?: number;
    nome?: string;
    email?: string;
    role?: UserProfileDTO.RoleEnum;
    dataCriacao?: string;
    fotoPerfil?: string;
}
export namespace UserProfileDTO {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


