/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDTO { 
    id?: number;
    nome?: string;
    email?: string;
    role?: UserProfileDTO.RoleEnum;
    dataCriacao?: string;
    fotoPerfil?: string;
    pontosHabilidade?: number;
    nivelHabilidade?: UserProfileDTO.NivelHabilidadeEnum;
    partidasJogadas?: number;
    partidasVencidas?: number;
}
export namespace UserProfileDTO {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
    export const NivelHabilidadeEnum = {
        Craque: 'CRAQUE',
        Mediano: 'MEDIANO',
        PernaDePau: 'PERNA_DE_PAU'
    } as const;
    export type NivelHabilidadeEnum = typeof NivelHabilidadeEnum[keyof typeof NivelHabilidadeEnum];
}


