/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoPontuacao } from './historicoPontuacao';
import { HistoricoTransferencia } from './historicoTransferencia';
import { GrantedAuthority } from './grantedAuthority';
import { Inscricao } from './inscricao';
import { ParticipacaoDesempenho } from './participacaoDesempenho';


export interface User { 
    id?: number;
    nome?: string;
    email?: string;
    password?: string;
    role?: string;
    enabled?: boolean;
    dataCriacao?: string;
    fotoPerfil?: string;
    pontosHabilidade?: number;
    nivelHabilidade?: User.NivelHabilidadeEnum;
    inscricoes?: Array<Inscricao>;
    desempenhos?: Array<ParticipacaoDesempenho>;
    historicoPontuacao?: Array<HistoricoPontuacao>;
    historicoTransferencia?: Array<HistoricoTransferencia>;
    username?: string;
    accountNonLocked?: boolean;
    authorities?: Array<GrantedAuthority>;
    credentialsNonExpired?: boolean;
    accountNonExpired?: boolean;
}
export namespace User {
    export const NivelHabilidadeEnum = {
        Craque: 'CRAQUE',
        Mediano: 'MEDIANO',
        PernaDePau: 'PERNA_DE_PAU'
    } as const;
    export type NivelHabilidadeEnum = typeof NivelHabilidadeEnum[keyof typeof NivelHabilidadeEnum];
}


